spring.application.name=Flufan
server.port=8080

server.error.include-message=always
server.error.include-binding-errors=always

spring.datasource.url=jdbc:h2:file:./bd1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# haslo do testowego konta google: 1234554321QwErTy.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mikivarstappan5@gmail.com
spring.mail.password=fazozlvayomdfywz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

stripe.publishableKey=pk_test_51R8fMF4EVajPE4SaH2TzvDRAFTMtxmItS1dkjGwvtdL4ujWZcTKmVSo8bWjcs6BQJ92gy3EGKv5jdshT6gnN2RXO00Ozfhdtvy
stripe.secretKey=sk_test_51R8fMF4EVajPE4SaC85HaT9vgy0jm2mxvvVjBQoYtDKXo5rPQWH9M4pfory6f78nIr8xniIkyIUZoisWoVWTa6WJ00KJe8JA5k
stripe.webhook.secret=whsec_XXXXXXXXXXXXXXXXXXXXXXXXXXXX
stripe.successUrl=http://localhost:8080/success
stripe.cancelUrl=http://localhost:8080/cancel

# Authentication with Google
spring.security.oauth2.client.registration.google.client-id=516773543712-10d6gjrkvmd0irva21jsv5jpegbfgn44.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# Authentication with Facebook
spring.security.oauth2.client.registration.facebook.client-id=XXX
spring.security.oauth2.client.registration.facebook.client-secret=YYY
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.facebook.client-name=Facebook

spring.security.oauth2.client.provider.facebook.authorization-uri=https://www.facebook.com/v12.0/dialog/oauth
spring.security.oauth2.client.provider.facebook.token-uri=https://graph.facebook.com/v12.0/oauth/access_token
spring.security.oauth2.client.provider.facebook.user-info-uri=https://graph.facebook.com/me?fields=id,name,email
spring.security.oauth2.client.provider.facebook.user-name-attribute=id
