spring.application.name=Frinkan
server.port=8080

server.error.include-message=always
server.error.include-binding-errors=always

spring.datasource.url=jdbc:h2:file:./bd1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ramzesrozpocki@gmail.com
spring.mail.password=bhhpiyqmqwivqxcr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

stripe.publishableKey=pk_test_51R8fMF4EVajPE4SaH2TzvDRAFTMtxmItS1dkjGwvtdL4ujWZcTKmVSo8bWjcs6BQJ92gy3EGKv5jdshT6gnN2RXO00Ozfhdtvy
stripe.secretKey=sk_test_51R8fMF4EVajPE4SaC85HaT9vgy0jm2mxvvVjBQoYtDKXo5rPQWH9M4pfory6f78nIr8xniIkyIUZoisWoVWTa6WJ00KJe8JA5k
stripe.webhook.secret=whsec_XXXXXXXXXXXXXXXXXXXXXXXXXXXX
stripe.successUrl=http://localhost:8080/success
stripe.cancelUrl=http://localhost:8080/cancel

## Google Login Configuration
#spring.security.oauth2.client.registration.google.client-id=525630124112-d6u53hv3grp8qq4ec7kab26uk4cgmlq0.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#spring.security.oauth2.client.registration.google.scope=openid,profile,email
#
## Facebook Login Configuration
#spring.security.oauth2.client.registration.facebook.client-id=TWÓJ_FACEBOOK_CLIENT_ID
#spring.security.oauth2.client.registration.facebook.client-secret=TWÓJ_FACEBOOK_CLIENT_SECRET
#spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#spring.security.oauth2.client.registration.facebook.scope=email,public_profile
#
## Apple Login Configuration
#spring.security.oauth2.client.registration.apple.client-id=TWÓJ_APPLE_CLIENT_ID
#spring.security.oauth2.client.registration.apple.client-secret=TWÓJ_APPLE_CLIENT_SECRET
#spring.security.oauth2.client.registration.apple.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
#spring.security.oauth2.client.registration.apple.scope=name,email







# POSTGRESQL configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/registration
#spring.datasource.username=
#spring.datasource.password=
#
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true



# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
## database
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
##spring.datasource.url=jdbc:mysql://localhost:3306/newdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
##spring.datasource.username=root
##spring.datasource.password=Root12345678
##spring.jpa.show-sql=true
##spring.jpa.generate-ddl=true
##spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.hbm2ddl.auto=update
#spring.datasource.url=jdbc:h2:file:./bd1
#spring.h2.console.enabled=true
#spring.h2.console.path=/console
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.datasource.platform=h2
#
#spring.devtools.restart.enabled=true
#
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=2MB
#spring.servlet.multipart.max-request-size=2MB
#
#openai.api.key=your_openai_api_key
#
## SMTP Server Configuration
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=x90063232@gmail.com
#spring.mail.password=tgaqfpjxesgqsawq
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


# SMTP Server Configuration
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=MY_EMAIL
#spring.mail.password=MY_PASS
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true